<div class="field deptor-account-number">
    <h2 class="title-deptor-account-number"><?php /* @escapeNotVerified */ echo __('Addition Information') ?></h2>
    <label class="label" for="title-deptor-account-number"><span><?php /* @escapeNotVerified */ echo __('Deptor Account Number') ?></span></label>
    <div class="control">
        <input type="number" id="deptor_account_number" name="deptor_account_number" required
               title="<?php /* @escapeNotVerified */ echo __('Deptor Account Number') ?>"
               class="input-text"
               autocomplete="on"
               data-validate="{required:true}"
        >
    </div>
</div>
